name: Run Docker Compose

on:
  push:
    branches:
      - main

jobs:
  docker-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for README.md
        run: |
          if [ ! -f README.md ]; then
            echo "README.md not found"
            exit 1
          fi

      - name: Create Frontend Network
        run: docker network create frontend

      - name: Run Docker Compose
        run: docker-compose up -d
