name: Check if file exists

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  action-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Check if file exists
        run: |
          if [ -f README.MD ]; then
            echo "File exists"
            exit 0
          else
            echo "File does not exist"
            exit 1
          fi
