name: Run Docker Compose

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your other steps here (e.g., installing Docker, setting up environment, etc.)

      - name: Run Docker Compose
        run: docker-compose up -d
