name: Check README exist

on:
  push:
    branches: [ "main" ]


  name: Check if file was created
  run: |
      if [ -f README.md ]; then
          echo "File exists"
          exit 1
      else
          echo "File does not exist"
      fi
      

