name: Maybe fail in case of file creation

on:
  push:

permissions:
  contents: read

jobs:
  action-scripts:
    runs-on: ubuntu-latest
    steps:

      - name: Check if file was created
        run: |
            if [ -f README1.MD ]; then
                echo "File exists"
                exit 1
            else
                echo "File does not exist"
            fi
