name: Check if file exists

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  action-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: start docker
        run: docker compose up -d

